### ISSUE TITLE
Spike: Create a resource in API Gateway for user management API

### ISSUE THREAD

**Issue by MCatherine1994** [bcgov/nr-forests-access-management#1008]
**Describe the task**
- [ ] Create a new resource in API Gateway for user management, change in terraform
- [ ] Create a new resource in API Gateway for the existing APIs, or how we handle the existing resource, change in terraform

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by ianliuwk1019** [comment]
Based on the reading, AWS has a feature called "**[multi-level base path mapping](https://aws.amazon.com/blogs/compute/using-multiple-segments-in-amazon-api-gateway-base-path-mapping/)**" that allows you to do this:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM25WQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b82239f48fcec9b0657d42d22dc0a48e0b85a829/image.png)

Something like this would be possible:
* "**/fam**/admin-management" (api)
* "**/fam**/app-access-control" (api)

However, that requires **Route53** and **Custom Domain** (to work with api-gateway), both we don't have.

**Comment by ianliuwk1019** [comment]
It seems the simplest is to create second api-gateway (**two api gateways**), since api-gateway cost only incurred by the number of requests, not the gateways itself.

Lots of benefits from online discussion and patterns, quote below:

> Top 6 Reasons Companies Adopt Multiple API Gateways
> 
> No. 1: External vs. internal traffic
> 
> Having separate API gateways enables you to enforce different security standards and protocols for external and internal users. You can also save money on internal API traffic. Or, you might need to add a new gateway to give customers and partners secure and simple access to complex legacy systems.
> 
> No. 2: On-premises vs. cloud deployment
> 
> Companies that opt for a hybrid architecture (keeping some applications on-premises while moving others to the cloud) usually require multiple API gateways.
> 
> No. 3: Central vs. local governance
> 
> Enterprises, especially large multinationals, often have multiple gateways because different business units or geographies have different needs and requirements.
> 
> No. 4: Old vs. new functionality
> 
> When an enterprise, or even a single business unit, outgrows the security, traffic management, or monitoring capabilities of an existing gateway, they often add another to close the functionality gap.
> 
> No. 5: Development vs. testing vs. staging vs. production environment
> 
> Most organizations we surveyed have multiple API gateways for different stages of the API lifecycle to avoid confusion about which endpoint to use at which time in which environment.
> 
> No. 6: Microservices vs. monoliths
> 
> Modern microservices architectures typically result in API traffic running in multiple service meshes and >Kubernetes-based clouds (from on-premises to AWS, Google, and Azure).

[AWS Api gateway pattern](https://docs.aws.amazon.com/prescriptive-guidance/latest/modernization-integrating-microservices/api-gateway-pattern.html):
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVBWQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--eea214b47774a956b929f8a21c202c70769cf6df/image.png)


However, since we don't have custom domain and when using two api gateways to separate two api(s)/lambda(s), we probably would still like to **distinguish these are for FAM api(s)/lambda(s)**, I am leaning toward these configuration for api-gateway parent path: 

> -  **/fam**-admin-management
> -  **/fam**-app-access-control
-  (**/fop**-review-approval-micro-service). Just example for easy future expansion, we don't have this case.

So for the implementation, we need to:
* adjust existing lambda, so the path isn't root (" **/** ") but (**/fam-app-access-control**), then test if it works, 
* then implement the second API gateway (**/fam-admin-management**)

**Comment by MCatherine1994** [comment]
I got a question, in the diagram above, the different Api Gateway connects to different lambdas, and different database. But we only have one database, we should be able connect two different lambda to the same db I believe?

**Comment by ianliuwk1019** [comment]
Hi @catherinecarlson , yes, Api Gateway only cares what backend that integrated with it, does not involve what dbs they are connecting to. It is a nice micro-service architect diagram from AWS as example on how to use Api gateway with several lambda with different functions.

**Comment by ianliuwk1019** [comment]
Add example to demo from our Tools space with "Two" different Api Gateway connecting to two different api lambdas.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenJoQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3032cc49f7516c92183c6121a0316d259d81782b/image.png)

AWS console test on original API gateway invoking original api lambda successfully:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBei9oQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b94ec6ea55e88e7ce3aeb56376cf83a87a8f275a/image.png)

AWS console test on new/example API gateway invoking new admin management api lambda successfully (with unauthenticated code returned):
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGJoQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ebe67daa07f197a198a5dfbbd821b672f60b6b5b/image.png)

Our Api gateway does not use custom domain host path(the host path is given by AWS). So at the beginning of the migration to the new split admin design, we don't necessary need to rename and adjust the original Api gateway resource path (root: "/" ). That makes it easier for the next implementation task to use terraform to add new Api gateway without impacting original Api gateway.
