### ISSUE TITLE
Hide BCeID user details if not the same organization

### ISSUE THREAD

**Issue by OlgaLiber2** [bcgov/nr-forests-access-management#1182]
**Describe the task**
As a delegated admin I want to only be able to see users within my organization (and their first and last names).

**Acceptance Criteria**
- [x] Update the Backend API for searching bceid user to check: if the requester's user type is B, then if his organization (business guid) is the same as the search result (return business guid)
- [x] Only return the search result with detail information if the business guid match
- [x] If not match, return error message to specify the permission issue because they are not in the same organization.
- [x] add test

**Additional context**
- Provide the FAM backends a way to access the user's identity type (IDIR vs Business BCeID) and a way to determine the Business GUID Main options are: 1. add to access token, 2. retrieve from Cognito via Cognito API (haven't validated if feasible but Conrad had mentioned as an option), 3. store and retrieve from user table - which would require a PIA update.
- FAM backend APIs dealing with BCeID user information need to check if the current user (if they are a BCeID user) has a business GUID (from their token) that matches the user record(s). If no match then remove attributes with personal information.
- This applies to any scenario where BCeID user details are displayed:

On validation of the id when granting access
On displaying user first & last name for granted user access. (we will try to make this check reusable, but this ticket can just target on the search bceid method)

We'll use the BCeID Business GUID attribute to check the organization of each user.

For any record not matching, redact / blank out / hide / remove attributes of personal information (PIA states that "no information about the result will be displayed", but we can at least confirm that the user id is valid). The result returned to the front-end will specify that information about the users cannot be displayed because they are not in the same organization.

Must be done after #1222 (backend)

See also #1184

**Comment by basilv** [comment]
I was thinking we'd have the guid stored in the fam users table and could fetch it from there. Or add it as a claim to the access token, that's probably the best approach.

**Comment by basilv** [comment]
Ian, you are right that we're missing this in the stories - I've added this to the delegated admin page. I keep flipflopping on which approach is best (add to access token vs lookup from user table). We should at least add the user identity type (IDIR vs Business vs ...) to the FAM access token, as that allows us for IDIR users to avoid needing to check the business GUID.

**Comment by basilv** [comment]
There's a third option, which is to query Cognito for the user information (Business GUID). If we were to store in our Postgres database, that would require a PIA update.

**Comment by ianliuwk1019** [comment]
Thank you Basil. 
Is the PIA is going to be another long process? It seems to me storing user's Business GUID is the best option.

By looking into backend code (not verified yet), our **Auth Lambda's "AWS event"** does have this attribute available `"custom:idp_business_id": "2DA5FA0A3E9F4A76825342BCCB861A15",` initially when user login; so we can store it without other hassle later on.

And the frontend does have ID Token (containing the Business GUID value) so **frontend can self-determine** the user identity type (IDIR vs Business vs ...) already. There is no extra need of this information either retrieving from backend or from Cognito again.

Cognito seems that initially it **does not provide/allow these custom attribute to be set in ACCESS TOKEN** (probably by the standard of OAuth, because it is user's identity and should be in ID Token), but I checked again and see Cognito has **restricted ability** for these custom attributes to be in **ACCESS TOKEN**; however it needs **advanced security enabled** (and **extra pricing**). I believe alternatively we can set this Business GUID value from the Cognito event attribute into ACCESS TOKEN at our Auth Lambda return (just feels having this
set into ACCESS TOKEN might be questionable from security review? since we already have user's GUID why extra business guid in ACCESS TOKEN that kind of question).

**Comment by MCatherine1994** [comment]
We have test business bceid accounts LOAD-3-TEST and TEST-3-LOAD-CHILD-1 from the same organization, LOAD-2-TEST is from a different organization.

**Comment by ianliuwk1019** [comment]
Verified and looks good to me.

QA: **DEV** environment.
Pre condition: "LOAD-3-TEST" is a delegated admin (FOM Reviewer).

* IDIR search for BCEID users (LOAD-2-TEST, LOAD-3-TEST):
   - Good. Can search on both.
* BCEID user (LOAD-3-TEST) search for IDIR user.
   ![Image](https://github.com/bcgov/nr-forests-access-management/assets/81595625/e8ff76e8-376d-4bb5-be95-0588b9bf5064)
   - Good (no need for this verify case)

* BECID user (LOAD-3-TEST) search for self:
   - Expected failed status.
      ![Image](https://github.com/bcgov/nr-forests-access-management/assets/81595625/d29da953-b034-4124-a237-05e209a3a42f)
   - However, message is confusing.
   - **Catherine mentioned we like to check with IDIM if this case can be enabled.**

* BECID user (LOAD-3-TEST) search for BCEID user (TEST-3-LOAD-CHILD-1) in the same organization:
  - Good. Expected success status.
     ![Image](https://github.com/bcgov/nr-forests-access-management/assets/81595625/bf0e476b-bdd7-4569-a608-9a65e0f58c0c)

* BECID user (LOAD-3-TEST) search for BCEID user (LOAD-2-TEST) in different organization:
   - Good. Expected failed status.
     ![Image](https://github.com/bcgov/nr-forests-access-management/assets/81595625/7b71e323-3b08-458c-9c4c-df433851e1a7)

* BECID user (LOAD-2-TEST) does not belong to any Admin Level and try to search for BCEID user:
   - Good. Expected failed status with no access.
      ![Image](https://github.com/bcgov/nr-forests-access-management/assets/81595625/18a018e9-a6b0-4ebf-8deb-ab9f34aeb26f)
   - **Just not sure if we want this error message to be a bit clear. (like, "Require admin access for operation." etc...)**
      However, this case won't happen on frontend I think.
      @MCatherine1994 @OlgaLiber2

**Comment by MCatherine1994** [comment]
Hi Ian, yes, the last case, when the user has no access in FAM, we can think of a better error description. I just copied from what we have before, thanks so much for verifying it.
