### ISSUE TITLE
/fam_application/{application_id}/role_assignment - POST

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-forests-access-management#122]
**As a** *Developer* **I want** *this endpoint** So That** *MVP req met*

**Additional Context**
POST - Info in:

role id
user_name (idir)
optional (forest client id)
example: if role id does not exist then gets created, if user_name does not exist it gets created, if forest_client_id is supplied a child role gets created on fom_submitter role. You would need to supply the fom_submitter role as role id.

Forest Client role naming convention is: role + forest_client_id
Role naming convention is: matches FOM req for now

FOM_SUBMITTER_00001011
In FAM: "FOM Submitter for Toko (00001011)"
in JWT: FOM_SUBMITTER { 00001011 }

**OOS:** validation of forest client or user id

**Acceptance Criteria**
- [ ] Given (Context), When (action caried out), Then (expected outcome)
- [ ] Given (Context), When (action carried out), Then (expected outcome)

**Definition of Done**
- [ ] Ready to Demo in Sprint Review
- [ ] Does what I have made have appropriate test coverage?
- [ ] Documentation and/or scientific documentation exists and can be found
- [ ] Peer Reviewed by 2 people on the team
- [ ] Manual testing of all PRs
--separate ticket for:
- [ ] Merged into DEV

**Comment by ianliuwk1019** [comment]
While troubleshooting the code for the endpoint, for some reason one orm model class (FamUserRoleXref - table: fam_user_role_xref) is missing this in my local from the orm model.py 
`
{"schema": "app_fam"} 
`
This is required for each orm table class or SqlAlchemy will not find the table. So the code would be similar like this:
![image.png](https://images.zenhubusercontent.com/62a9ff93d8506f14758ef03a/5782dbd8-ee19-498d-9746-12f31828dc9a)

According to SqlAlchemy, this can be set globally: 
![image.png](https://images.zenhubusercontent.com/62a9ff93d8506f14758ef03a/a2a3265c-a09b-42c7-927d-b002b553a1d7)

Although initially I did try, but due to my knowledge gap, I didn't make it work. Wondering if it is worth to create a new future ticket to experiment this setting for SqlAlchemy on FAM project.
@franTarkenton

**Comment by ianliuwk1019** [comment]
When working on unit testing for the crud code, I encounter strange error specific with unit test environment (**Sqllite**); **I don't see this happen with Postgresql**.
When **retrieving existing record** from a table (some tables, such as fam_user, fam_role etc..), unit test will throw error: (**ValueError: Couldn't parse datetime string: 'LOCALTIMESTAMP'**)
I did spend quite sometime trying to see what could be wrong but haven't found a cause of this problem yet. It is some conversion problem (**related to timestamp column**), not really sure if it is happening within SqlAlchemy conversion or Python type conversion related.
The '**LOCALTIMESTAMP**' seems to be specific for Postgresql dialect when marking a datetime column default (datatype: timestamp without time zone) and Sqllite does not have that (LOCALTIMESTAMP). Not sure if there is a general default one that will work for both Postgresql and Sqllite.
Need to talk with @franTarkenton @gormless87 to see if there is alternative solution or is there something I have missed in Python.
