### ISSUE TITLE
Update API documentation in wiki

### ISSUE THREAD

**Issue by MCatherine1994** [bcgov/nr-forests-access-management#1221]
**Describe the task**
Update our API documentation https://github.com/bcgov/nr-forests-access-management/wiki/API-Security, update documentation for the app access apis, and add documentation for  admin management apis

**Acceptance Criteria**
- [x] Review and update the existing documentation for backend apis
- [x] Follow the existing one to add documentation for the admin management apis

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by ianliuwk1019** [comment]
Looks good to me, thank you Catherine.

**Comment by MCatherine1994** [comment]
Hi Basil @basilv, when you have time do you mind review the updated API documentation? https://github.com/bcgov/nr-forests-access-management/wiki/API-Security thanks!!

**Comment by basilv** [comment]
@MCatherine1994  Some feedback:
- Spelling mistake "Aadmin Management Endpoints". 
- "prevent a user with lower privileges hacking into the executable for a low-privilege API" - should be "high-privilege API"
- I'm not sure how necessary the screenshots are vs just referencing the prod API documentation page.
- I'd like to see a link to our prod API documentation page added at the top of this page. 
- I'm surprised the call to /user_terms_conditions/user:validate is a post instead of a get

**Comment by MCatherine1994** [comment]
Please check the reply below, thanks!!

> [@MCatherine1994](https://github.com/MCatherine1994) Some feedback:
> 
> * Spelling mistake "Aadmin Management Endpoints".
              **Thanks fixed!** 
> * "prevent a user with lower privileges hacking into the executable for a low-privilege API" - should be "high-privilege API"
              **fixed** 
> * I'm not sure how necessary the screenshots are vs just referencing the prod API documentation page.
      **I feel sometimes I want to know the return result of the API, but maybe the link to PROD Api Gateway will help as well?**
> * I'd like to see a link to our prod API documentation page added at the top of this page.
      **The link to the Api Gateway Swagger? I added to the link to the title**
> * I'm surprised the call to /user_terms_conditions/user:validate is a post instead of a get
