### ISSUE TITLE
Functioning end2end Hello_FAM_API

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-forests-access-management#125]
**As a** *Developer* **I want** *a functioning e2e API example* **So That** *the FAM API can be patterned*

**Additional Context**
*** able to make db connection from API

**Acceptance Criteria**
- [x] Given (Context), When a deployment happens , Then pipeline creates lambda function
- [x] Given (Context), When database is queries , Then the name of the application is returned
- [x] When endpoint is hit then we get back a result that includes some data from the database

**Definition of Done**
- [x] Ready to Demo in Sprint Review
- [x] Does what I have made have appropriate test coverage?
- [ ] Documentation exists and can be found
- [ ] Peer Reviewed by 2 people on the team
- [x] Manual testing of all PRs
- [x] Merged into DEV

**Comment by ConradBoydElliottGustafson** [comment]
OK, the version of the code in DEV gets the credentials from a secret and connects directly to the DB.

**Comment by ConradBoydElliottGustafson** [comment]
I think this meets the requirements now (see checklist).

The database connection is a direct connection. It would be better to use the RDS Proxy service so that we can configure database connections. I'm investigating that now. It could be a separate ticket, but I'll leave it on this one for now.

@ArogeG
