### ISSUE TITLE
Define and test database migration flow 

### ISSUE THREAD

**Issue by franTarkenton** [bcgov/nr-forests-access-management#128]
**As a** *(User Type/Persona)* **I want** *(Feature/enhancement)* **So That** *(Value, why is this wanted, what is the user trying to accomplish)*

**Additional Context**
- Proposing that the definition of truth be the ORM model
- This ticket will verify that we can create migrations from the ORM model, that can then be transitioned to flyway migrations
- should provide a definition for how this works
- ticket will define how to create an alembic migration ->
- from the alembic migration generate a *flyway* migration

**Acceptance Criteria**
- [ ] Given ?, When a database change is created in the model, there is a defined process for how that migration will get implemented in the database

**Definition of Done**
- [ ] Ready to Demo in Sprint Review
- [ ] Does what I have made have appropriate test coverage?
- [ ] Documentation and/or scientific documentation exists and can be found
- [ ] Peer Reviewed by 2 people on the team
- [ ] Manual testing of all PRs in Dev and Prod
- [ ] Merged

**Comment by franTarkenton** [comment]
* Determined that the @ianliuwk1019 has encorporated the changes in the migrations defined in the PR: https://github.com/bcgov/nr-forests-access-management/pull/100.  Propose we delete that pr
* Figured out how to get alembic to name its migrations in a way that corresponds with the naming convention that flyway wants to use
* identified manual process for how to generate the flyway migrations from alembic migrations
* working on script to automate the conversion from alembic to flyway scripts

**Comment by franTarkenton** [comment]
Noticed that the seed / fixture data identified in the flyway V2 migration is not also included in the alembic migrations.  

The following shows how data can be added using alembic migrations:
https://github.com/bcgov/nr-forests-access-management/blob/e0301b55b329a687a4d3ed62e798b04342b56446/server/backend/api/alembic/versions/V2_first_application.py#L207

**Comment by ianliuwk1019** [comment]
Just a note.
**problem**:
I was running into trouble for using Alembic '--autogenerate' to create a delta migration script. Locally at this moment it did not compare my current db state and create the delta; instead, it creates whole new 'Create' script for all tables.

**Get around the problem**:
Kevin points out he has found a solution for this gotcha issue from Alembic and would include the fix for 'autogenerate'. From talking to Kevin, it seems Alembic only use default schema while our database schema is different '**app_fam**' so Alembic can't detect it to create the delta script. The Context.config will need to include this setting:
**include_schemas=True**
Reference: https://vistacoder.com/forums/alembic-sqlalchemy-does-not-detect-existing-tables
