### ISSUE TITLE
Update role selection to use radio in table

### ISSUE THREAD

**Issue by MCatherine1994** [bcgov/nr-forests-access-management#1456]
**Describe the task**
Update the role selection dropdown in Grant Access and Grant Delegated Admin form to become a table with radio selection and role description as in the new design. Start with single selection for now. 

**Acceptance Criteria**
- [x] Backend get my access api return role description
- [x] Regenerate client code for frontend
- [x] Frontend create a role table component 
- [x] Update the two forms to use role table for role selection
- [x] Update test if needs

**Additional context**
- Add any other context about the task here.
- Or here

https://www.figma.com/design/VuQBlZZ1PmGUlEBJriyzo5/Manage-permissions?node-id=2149-30454&t=n7wOvIiT2h9I2AVw-4

**Comment by OlgaLiber2** [comment]
@NickSaglioni here's the link to figma https://www.figma.com/design/VuQBlZZ1PmGUlEBJriyzo5/Manage-permissions?node-id=2149-30454&t=n7wOvIiT2h9I2AVw-4

**Comment by MCatherine1994** [comment]
Hi Nick @NickSaglioni , just fyi, we still need to keep the current role selection dropdown component, cause we'll use the dropdown later as well. Thanks!

**Comment by NickSaglioni** [comment]
The `Checkbox` component used in Figma is not being used for now, replaced by the `RadioButton` component. This is because `Checkboxes` in definition accept multiple selections, which the application is not prepared yet. `RadioButton` only accepts one value, so it was used in this case. It should be replaced with Checkbox once multiple values could be used.
