### ISSUE TITLE
Add client details to GET user_role_assignment endpoint

### ISSUE THREAD

**Issue by craigyu** [bcgov/nr-forests-access-management#1638]
**Description:** Add ClientDetails for each FamApplicationUserRoleAssignmentGetSchema in the paginated result of GET user_role_assignment endpoint

**Acceptance Criteria**
- [x] Integrate the /api/clients/search endpoint from Forest Client API 
- [x] Add Client name property to response body
- [x] modify frontend column to display client name and client number
- [x] sort by client number
- [x] Change column name from `Client number` -> `Organization`
- [x]  Add tests!

**Additional context**

**Comment by ianliuwk1019** [comment]
FC API is reacting interestingly (TEST environment, `/api/clients/search`):
![Image](https://github.com/user-attachments/assets/ff1eea72-86c9-4566-8882-d8aa02d1fe52)

* Same (2) ids searching, it responds with ranging from 950ms to ~3s; the range seems a bit inconsistent, not sure if it is due to my network or on server end.
* It can accept the parameters with `&id=id1&id=id2` or `&id=id1,id2`. not sure if it is a flexible feature or is it something we need to watch out to choose one to use.
@craigyu @basilv

**Comment by ianliuwk1019** [comment]
Hi @OlgaLiber2 , how do we like to add "client name" to frontend (table below)? I can't find the mockup. @craigyu 
![Image](https://github.com/user-attachments/assets/348bb537-ce76-4857-b9fd-94255fb16cb4)

Example:
Akieca Explorers Ltd. (**00001011**)
**00001011** (Akieca Explorers Ltd.)
**00001011** - Akieca Explorers Ltd.

**Comment by OlgaLiber2** [comment]
@ianliuwk1019 my figma crashed and I need to reinstall. Can you reach out to Marina please? She will can point you to the mockup.
