### ISSUE TITLE
Create and deploy Lambda function that queries the FAM db with each authentication event

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-forests-access-management#21]
This is the task that implements the lambda function to query FAM and update the JWT. Detailed design is in the dependent task (#24).

AC:
Pick a technology (Python)
Extract the inputs from the incoming request
Implement and test the actual SQL query
Parse the query results and convert to formatted JSON for the response (adding to the JWT as part of the response) 
Handle error scenarios (no data found, etc.)

Deploy the authorization lookup lambda
Deploy any permissions required for the Lambda to query the database

**Comment by franTarkenton** [comment]
## Summarizing action items that came out of pair programming session (10-19-2022)

* Harmonize the database setup / configuration for local development on both flyway and the api so that either database can be used interchangeably for development
* Define a standardized location for the virtual environment used for local development, and update the vscode config
* Database migrations:
	* review the db migration 11 and get it working in Alembic so that the alembic migrations can be cascaded down to flyway
	* Also create a unique constraint on the combination of cognito_client_id and application_id for the table fam_application_client
* fix the VS code test config so that it works for all the various pytests
* create a readme that defines the local dev setup for developing the auth function
* refactor / cleanup work that was completed during the pair programming session:
	* identify and implement additional tests required
	* move setup code out of test and into fixtures to promote re-use
	* potentially modify the lambda module into OO
	* fix linting errors / warnings

**Comment by ConradBoydElliottGustafson** [comment]
Here's a direct link to the wiki page that defines the behaviour: https://github.com/bcgov/nr-forests-access-management/wiki/Authorization-Mechanism

**Comment by ConradBoydElliottGustafson** [comment]
Seems to have an error in DEV. Need to debug and get it working.
