### ISSUE TITLE
Generate client-side API code

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-forests-access-management#300]
**As a** *Developer* **I want** *to generate the javascript for the front-end* **So That** *I don't have to do it manually*

**Additional Context**
- Currently front-end used Axios library for HTTP request.
- Official openapi-generator reference: https://openapi-generator.tech/docs/generators; and we will use 'typescript-axios' for generator for frontend.
-- OOS - integration with front-end

**Acceptance Criteria**
- [ ] run API locally, backend exposes API spec (json), run generator to create http client for front-end

**Definition of Done**
- [ ] Ready to Demo in Sprint Review
- [ ] Does what I have made have appropriate test coverage?
- [ ] Documentation and/or scientific documentation exists and can be found
- [ ] Peer Reviewed by 2 people on the team
- [ ] Manual testing of all PRs in Dev and Prod
- [ ] Merged

**Comment by ianliuwk1019** [comment]
Found this npm library, [openapi-client-axios](https://www.npmjs.com/package/openapi-client-axios), that may be of more interest to us.

After initial npm installation and do:
```
const api = new OpenAPIClientAxios({ definition: './openapi.json' });
api.init();
```
without any other configuration to quickly see if app run fine, but when frontend server starts, the browser can't open app with error:
```
url.js:3 Uncaught ReferenceError: process is not defined
    at node_modules/@apidevtools/json-schema-ref-parser/lib/util/url.js (url.js:3:29)
    at __require2 (chunk-IKJM6GHQ.js?v=c7842f0a:18:50)
    at node_modules/@apidevtools/json-schema-ref-parser/lib/pointer.js (pointer.js:6:13)
    at __require2 (chunk-IKJM6GHQ.js?v=c
```
Not sure what it is about, need to investigate it.

**Comment by ianliuwk1019** [comment]
I comment out the `new OpenAPIClientAxios() ` and also its `api.init()` and problem persists.

The problem seems to be very likely that the openapi-client-axios uses some lib that uses other lib that is with node environment (function using node 'process') but not compatible with browser; and most likely requires some extra configuration in vite.config.ts to solve the problem.

I can resolve issue as far as in local "npm run dev" to work and being up the frontend page but the production build (although it builds) but open up the frontend page in browser will have other problem:
`
Uncaught TypeError: Cannot convert undefined or null to object
`
To test if production build work, just do `npm run build` and in the 'dist' directory, run `npx http-server -p 5173` to start server.

Spent lots of time but couldn't get it resolved. This is my branch: https://github.com/bcgov/nr-forests-access-management/tree/feat/300-openapi-client--use-openapi-client-axios-lab1

**Comment by ianliuwk1019** [comment]
Previous approach using "**openapi-client-axios**" requires our Vue app to have some extra configuration in Vite and may be difficult to figure it out. I also create a second branch to use [OpenAPI Generator approach](https://openapi-generator.tech/docs/installation) at this branch: https://github.com/bcgov/nr-forests-access-management/tree/feat/300-openapi-client--use-api-code-generation-lab2
Only partial code for now before my vacation. I haven't reach the point that I can try generating the initial client code based on documentation because my environment (Windows WSL) does not have java and having problem installing java right now. The OpenAPI Generator needs java dependency.
@basilv

**Comment by ianliuwk1019** [comment]
Continued to work on this on [branch](feat/300-openapi-client--use-api-code-generation-lab2).
The mini npm project (in folder "client-code-gen") now can generate FAM API client from OpenAPI spec successfully. It probably can be improved more but for now we have the starter.
We will need to have another ticket to integrate this generated client (library), figure out how to setup axios instance for this client, passing base_url for backend (for each environment, including locally) and other meta info, and used in frontend code.
@basilv @gormless87

**Comment by ianliuwk1019** [comment]
Switch to this [branch](https://github.com/bcgov/nr-forests-access-management/tree/feat/300-openapi-client-generation) and created a [PR-353](https://github.com/bcgov/nr-forests-access-management/pull/353).

**Comment by ianliuwk1019** [comment]
Current PR merged.
We would like to have separate PR to make this generation in docker and output generated client code for consistency and not needed to have java environment setup locally.

**Comment by ianliuwk1019** [comment]
Added docker generate option into the generate npm script and incorporated the changes (including readme) into the current [PR-358](https://github.com/bcgov/nr-forests-access-management/pull/358).

Found out the [OpenAPI-generator](https://hub.docker.com/r/openapitools/openapi-generator-cli/tags) does provide docker version for consume, so we don't need to write our own; and the generator options are still the same as previous ones as using cli option.
I initially I had permission issue with npm not able to access docker generated shared folder, but seems it was probably due to I was messing around the way it generates and was doing some experiment. I didn't encounter issue further afterward.
@basilv
