### ISSUE TITLE
Back-end Integrate with Forest Client API  - Phase 1

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-forests-access-management#305]
As a an application access administrator I want to see a list of forest client So That I can select a forest client for an assignment.

Additional Context
-- Integrate Forest Client API with frontend and back-end for validation.
--Allow users to select and search for a forest client by forest organization name/client  and ID.
--If Forest Client does not exists, return a message "Forest Client cannot be Found".
--Security - must be logged FAM user in order for FC API to work

Acceptance Criteria

From the front end, can execute a search and get results returned from the Forest Client API

Definition of Done
Ready to Demo in Sprint Review
Does what I have made have appropriate test coverage?
Documentation and/or scientific documentation exists and can be found
Peer Reviewed by 2 people on the team
Manual testing of all PRs in Dev and Prod
Merged

Cloned from #179

**Comment by gormless87** [comment]
Need to connect with Team Alliance on their Forest Client API

**Comment by franTarkenton** [comment]
thinking this could be further broken down into two tickets
* wrap forest client api into our api
    * to support search of forest client based on forest client name or forest client number
* a ticket that would address, how and when we would integrate forest clients into our database.
    * thinking this would not take place during a search, but rather when we we add a new user/role assignment takes place

**Comment by ianliuwk1019** [comment]
Got some information from Maria today:
- Direct link to Forest Client api-docs: https://nrfc-api-prod-backend.apps.silver.devops.gov.bc.ca/
- Need to request access through API Services Portal: https://api.gov.bc.ca/devportal/api-directory
- Currently the **Forest Client Api has not been published** yet @ API Services Portal due to some work on database vault.

Q: how to request access through API Services Portal for Forest Client Api if it is available?

**Comment by ianliuwk1019** [comment]
Got some information from Maria today:
- Direct link to Forest Client api-docs: https://nrfc-api-prod-backend.apps.silver.devops.gov.bc.ca/
- Need to request access through API Services Portal: https://api.gov.bc.ca/devportal/api-directory
- Currently the **Forest Client Api has not been published** yet @ API Services Portal due to some work on database vault.

Q: how to request access through API Services Portal for Forest Client Api if it is available?

**Comment by ianliuwk1019** [comment]
It may not be available next week.
Reply from Alliance Team:

> Hi Ian,
> 
> Thanks for the reply! We'll try to make it published within the next sprint, hopefully within the next 3 weeks. I'll keep you posted. Also I'll add your one search endpoint request to our backlogs.
> 
> Thanks,
> Catherine
>

**Comment by ArogeG** [comment]
Team Alliance is planning to publish the Forest Client API by next week Friday at which point we can request for access through the API services portal. In the interim, we can begin working on the FAM backend for  the forest client API.

**Comment by ArogeG** [comment]
Team Alliance is planning to publish the Forest Client API by next week Friday at which point we can request for access through the API services portal. In the interim, we can begin working on the FAM backend for  the forest client API.

**Comment by MCatherine1994** [comment]
Forest client api specification: 
test: https://nr-forest-client-api-test.api.gov.bc.ca/
prod: https://nr-forest-client-api-prod.api.gov.bc.ca/

**Comment by ianliuwk1019** [comment]
Forest Client API access requested (status: waiting):
![image.png](https://images.zenhubusercontent.com/62a9ff93d8506f14758ef03a/c7eb6eed-b13b-4381-b33e-3e6852948ef1)

**Comment by ianliuwk1019** [comment]
Got "**TEST**" environment API Key: 4r0dn5wC0JTs6N1tdw6NDzpjBRQwEJ6u
Using Postman and try:
* `https://nr-forest-client-api-test.api.gov.bc.ca/api/clients/findByClientNumber/00001011`
   result: 
```
{"clientNumber":"00001011","clientName":"AKIECA EXPLORERS LTD.","clientStatusCode":"ACT","clientTypeCode":"C","acronyms":[]}
```
* `https://nr-forest-client-api-test.api.gov.bc.ca/api/clients/findByNames?page=1&size=10&clientName=AKIECA EXPLORERS LTD.&clientTypeCode=C`
   result: Getting **no result** back, strange. It is the `clientName` and `clientTypeCode` got back from first request to use in this request.

**Comment by basilv** [comment]
Probably an issue with the spaces in the URL. I'm pretty sure spaces aren't allowed (get mapped to %20).

**Comment by ianliuwk1019** [comment]
Good catch but I tried, still having no luck...

**Comment by basilv** [comment]
Did you try a different forest client with no spaces in the name?

**Comment by ianliuwk1019** [comment]
`https://nr-forest-client-api-test.api.gov.bc.ca/api/clients/findByClientNumber/00000020`
=> `{"clientNumber":"00000020","clientName":"DAINACK","legalFirstName":"HONORINE","legalMiddleName":"Margaret","clientStatusCode":"DAC","clientTypeCode":"I","acronyms":[]}`

`https://nr-forest-client-api-test.api.gov.bc.ca/api/clients/findByNames?page=1&size=10&clientName=DAINACK&clientTypeCodes=I`
=> `[]` empty... "**Note**": param is "clientTypeCodes" not "clientTypeCode" based on api spec.

**Comment by ianliuwk1019** [comment]
I wasn't aware the **`page`** parameter needs to be starting at "0", not "1" (normally I thought it should be 1 the first page).
Can also ignore `page` parameter.
```
https://nr-forest-client-api-test.api.gov.bc.ca/api/clients/findByNames?page=0&clientName=AKIECA EXPLORERS LTD.
or
https://nr-forest-client-api-test.api.gov.bc.ca/api/clients/findByNames?clientName=AKIECA EXPLORERS LTD.
```
Both works:
```
[
    {
        "clientNumber": "00001011",
        "clientName": "AKIECA EXPLORERS LTD.",
        "clientStatusCode": "ACT",
        "clientTypeCode": "C",
        "acronyms": []
    }
]
```

**Comment by ianliuwk1019** [comment]
As tested it out locally from frontend to backend (locally - implementation in progress), this is json structure returned from backend to browser console:
![image.png](https://images.zenhubusercontent.com/62a9ff93d8506f14758ef03a/72e98d3a-2ce0-4a15-9873-3d5324af3aa2)
This should be a good starting for frontend.

**Comment by ArogeG** [comment]
Moving comment below  from **nr-fom/280**
"These are the client status from "Forest Client API":

ACT (Active)
DAC (Deactivated)
DEC (Deceased)
REC (Receivership)
SPN (Suspended)
FAM backend will return to FAM frontend with mapping of client status codes (from Forest Client API) with: "Active (Active)" and "Inactive (Inactive) - Deactivated, Deceased, Receivership, Suspended".
For the "backend" validation before saving user-role assignment, I assume only the "exists forest client with Active status" can be granted for access. However, curious if current "bulk users role assignment imported from the script include all other client status other than Active" and will this "Active" status restriction affects the script import. #481
Won't check "client type" before saving, since all types are valid including "individuals", see comment from #179.
@basilv @ianliuwk1019 These are the client status from "Forest Client API":

ACT (Active)
DAC (Deactivated)
DEC (Deceased)
REC (Receivership)
SPN (Suspended)
FAM backend will return to FAM frontend with mapping of client status codes (from Forest Client API) with: "Active (Active)" and "Inactive (Inactive) - Deactivated, Deceased, Receivership, Suspended".
For the "backend" validation before saving user-role assignment, I assume only the "exists forest client with Active status" can be granted for access. However, curious if current "bulk users role assignment imported from the script include all other client status other than Active" and will this "Active" status restriction affects the script import. #481
Won't check "client type" before saving, since all types are valid including "individuals", see comment from #179.
@basilv @ArogeG
"

**Comment by ianliuwk1019** [comment]
PROD API Token is requested and approved.
The api token setup is configured for our FAM all environments and currently is in PR.
Note! - **Current PROD Forest Client API isn't accessible**; contacted Forest Client API Team last week and is currently being investigated.

**Comment by ianliuwk1019** [comment]
Got reply back from Maria that Forest Client API Prod is working now.

**Comment by ianliuwk1019** [comment]
Sorry @ArogeG , as disussed, we can wait for Nick's frontend work #179 so we can deploy both backend and frontend together for this feature as a whole set. Currently if only deploy backend, it will not work from frontend side. Thanks.

**Comment by ianliuwk1019** [comment]
@ArogeG if you like to test it from swagger/OpenAPI page, please let me know and I can help with that.
