### ISSUE TITLE
Duplicate Role Assignment

### ISSUE THREAD

**Issue by ArogeG** [bcgov/nr-forests-access-management#335]
**Describe the bug**
On the FAM Grant Access screen, I am able to submit multiple role assignment requests for the same user on the same branch. FAM should not allow duplicate role assignment records to be created. An alert should be returned indicating that "user role assignment Record already exists"

**To Reproduce**
1. Go to 'https://d2solh97t525i7.cloudfront.net/grant...'
2. Select Application 'FOM'
2. Click on 'Grant Access.'
3. Enter BCeID, Role and Click on Grant Access
4. Repeat the Steps above...

**Actual Behavior**
The system allows duplicate records to be created.

![image.png](https://images.zenhubusercontent.com/62a1029ce9497c39c087ab8b/eb1acc71-845a-43d0-bc8a-16d3a9de2897)

**Expected behavior**
An alert is returned with a message saying record already exists
**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge

**Additional context**
This is a backend fix, but will require frontend modifications to accommodate.

**Comment by ArogeG** [comment]
@NickSaglioni @basilv  please can you confirm that this ticket will not prevent users from being added to multiple forest client organizations?

**Comment by basilv** [comment]
I can confirm the 2nd attempt to add the same role succeeds (displaying a success message) without actually adding a 2nd role. Question whether we want to display a warning/error instead or not.

Adding two user ids with different cases (e.g. BVANDEGR vs bvandegr) results in duplicate entries. At least for IDIR, I suspect it is case insensitive, or we have a bug because I log in with 'bvandegr' in lowercase, but access is defined based on 'BVANDEGR' in upper-case.

Unable to test GBhola's scenario right now (grant same id access to multiple forest clients - same and different) due to environment issues, but I think its a great test.

**Comment by NickSaglioni** [comment]
Thanks @basilv for the tests. Your question is pertinent, should we display an error message when there is an attempt to add an existing role to a user? Also, for the case insensitive scenario, maybe we should apply the uppercase for the IDIRs before adding the entry to the DB, as they usually are in uppercase anyways, just to prevent duplication.
