### ISSUE TITLE
Apply security to all FAM api endpoints

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-forests-access-management#347]
**Describe the task**
I (Conrad) wrote all the code to secure the endpoints. If I apply it to all the endpoints, it will be checking for valid JWT and role membership. Valid JWT is not really a problem, but the role membership is. I didn't want to block the front-end developers so what I did was create some new endpoints for testing. 

GET fam_applications/secure is the same as GET fam_applications but it validates the token
GET fam_applications/authorize validates the token and also checks to see if the user has at least one FAM admin role
GET fam_applications/{application_id}/fam_roles/authorize does the same thing as fam_applications/{application_id}/fam_roles but it also validates the token and makes sure that you have the admin role corresponding to the application specified by "application_id"

For this ticket, we should delete the 3 test endpoints described above and apply the validation and authorization logic to all the endpoints (using the test endpoints as a sample). It's not complicated -- literally 1 line of copy/paste for each endpoint.
Update: The "User Role Assignment" endpoints needed more logic than what was originally developed and tested for the "Application" endpoints. New custom code in that router to handle it, plus some refactoring to make it all work smoothly.

**Acceptance Criteria**
- [x] test endpoints are deleted
- [x] correct security rules are applied (as per https://github.com/bcgov/nr-forests-access-management/wiki/API-Security)
- [x] all existing unit tests pass (had to update all the router tests to be aware of security context)

Stretch:  -bumps estimate to a 5
- [ ] new unit tests to verify that the endpoints are all secure

Bonus: 
- [x] All the "User" and "Role" endpoints now return 501 (not implemented) so there is no security risk.
- [x] Refactored all the test code to live in the same directory 

**Additional context**
Lots of code smells in the API code -- mostly naming of variables and commented code. I'd like to delete most of the commented out code, as well as the endpoints that we are not using, but I'm afraid Ian will get mad if he has to regenerate the front-end again!!

**Comment by basilv** [comment]
@ConradBoydElliottGustafson This doesn't seem to be working. I just tested locally from frontend, and get a HTTP 405 method not allowed error calling the first secured api: 172.25.0.1:59786 - "GET /api/v1/fam_applications/secure HTTP/1.1" 405 Method Not Allowed. The backend logs show no additional details. I've confirmed your code changes are in the main branch. The openAPI docs page locally doesn't show these endpoints either. 

When I try the api/v1/fam_applications/1/fam_roles/authorize endpoint, I get a HTTP 404 not found error, which is different from the 405.

The api/v1/fam_applications/authorize gives me a HTTP 405 Method Not Alllowed.

Some of these endpoints I tested directly in the fam-api docker container using curl. With no security header supplied I would expect a 403 response instead of the 404/405. The test in the front-end I believe was supplying a valid token, so the fam_applications/secure call I would expect to succeed. The response headers includes "allow: DELETE" which I think is saying only a HTTP DELETE is accepted for this endpoint, when it should accept a get.
See screenshot: ![image.png](https://images.zenhubusercontent.com/62a269d303643f51cc9d7898/6b5caedc-0699-411e-bb18-fbee402b6d6e)

**Comment by ConradBoydElliottGustafson** [comment]
@basilv Very strange. I just re-ran my local manual test and it works fine. Did you docker-compose up from the root of the project? Are you sure the images are not stale? My test is to go to the /docs endpoint and try the API from there, but the curl command can be copied and used as well.

**Comment by basilv** [comment]
@ConradBoydElliottGustafson issue was due to stale local image. Now confirmed working with /secure and /authorize

**Comment by basilv** [comment]
@ConradBoydElliottGustafson my test of fam_applications/{application_id}/fam_roles/authorize did return but didn't filter results as expected. When I deleted my access to FOM_ACCESS_ADMIN role, I would expect this endpoint to return no results, but it still returns all the FOM roles. So I'm not sure if I misunderstood what you set up.

**Comment by basilv** [comment]
Oh wait, I would need to log off and log on again to refresh my token's access...

**Comment by basilv** [comment]
Hmm, no change in behavior after logging off and on, with my access to FOM_ACCESS_ADMIN removed. So I'm not sure what's happening with the authorize_app check....
I've confirmed in the database that the user_role_xref table only links me with FAM_ACCESS_ADMIN.

**Comment by basilv** [comment]
Successfully tested the roles endpoint that it returns a 403 if the user doesn't have access to the app.

Identified issue that the applications authorized endpoint needs to only return applications that the user is authorized for (belongs to the {app}_access_admin role.
