### ISSUE TITLE
Create and Update User not populated correctly

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-forests-access-management#367]
The create_user and update_user database fields should be populated based on the actual user name (from the JWT token), not use the database user as it is currently doing.

As a security analyst I want to be able to audit user activity in FAM for security investigations.

AC: 1 - create new record (grant access access) inspect database to ensure records populated approp.

Additional Info:

Ticket #359 has some improvement on using FastAPI global "Depends" when possible, that will reduce code needed for authorization in the business code itself. Also there are "advanced dependencies" and "advanced security" that are worth considering for our FAM implementation as well.
Partial work was done, maybe worth taking advantages of it when we work on this ticket.
The branch for the improvement is here: https://github.com/bcgov/nr-forests-access-management/tree/feat/359-auth-dependency-injection-partial-work.

**Comment by ianliuwk1019** [comment]
Conrad and I had a conversation for how this should work (for JWT token) and what to use to save the user.
For this moment, we would like to revert 'main' back to previous state before this task. And I will create another branch to use the "username" field in the access_token instead. This is the field for Cognito user id (not the username from IDIR or BCEID). We decided to use this id instead of IDIR/BCEID "custom:idp_username" field as it is easier and no need to mess around jwt ID token. Also we have all information (including user_name) in our "fam_user" linking to this Cognito user id. So create_user and update_user are good to use this value. Using this value we can also query "fam_user" to find out the username if it is needed. @ArogeG @gormless87 @ConradBoydElliottGustafson

**Comment by ArogeG** [comment]
My understanding is the cognito ID will be displayed in the Create User and Update User fields. I don't think this has been implemented in Dev. The create_user and update_user fields still displays sysadmin or proxy user.
![image.png](https://images.zenhubusercontent.com/62a1029ce9497c39c087ab8b/063104a4-a6b8-4fbd-8bb5-ba5ccb735b11).

**Comment by ianliuwk1019** [comment]
Hi @ArogeG ,
Thank you so much for verifying it.
The code has been merged last week but the latest deployment to 'DEV' is 2 weeks ago, so this change has not been deployed yet.
Maybe when you feel we have enough new fixes/features in DEV then you can call for a DEV deployment and then we can verify again.
Thank you Gbola.

**Comment by ArogeG** [comment]
Verified, the system stores the Create by field on FAMDB with the Cognito username attribute. ![image.png](https://images.zenhubusercontent.com/62a1029ce9497c39c087ab8b/63c37456-4375-4472-bd73-c67df803ce75).
