### ISSUE TITLE
Uptime monitor

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-forests-access-management#411]
**Describe the task**
We need alerting for our AWS infrastrucure

**Acceptance Criteria**
- [ ] CloudWatch dashboard for 400/500 error
- [ ] CloudWatch alert(s)
- [ ] documented

**Additional context**
-

**Comment by basilv** [comment]
I configured an initial alert, it is notifying just me so far.
(I need to know the email address for the Fingerprint DL to use in the alert.)

**Comment by basilv** [comment]
Added SIBIFSAF@Victoria1.gov.bc.ca to the alert. Not sure the alarm condition is quite right, but this can be tweaked.

**Comment by ArogeG** [comment]
@basilv, a couple of questions below:

- It looks like alarms were created only for Lambda errors, do we need to create alarms for others such as API gateway errors 400 & 500, concurrent executions and latency? 

- Do we need to have further conversations on the thresholds? 

- Are we monitoring the duration or time it takes for the lambda to run, we might have discussed this earlier today?

**Comment by basilv** [comment]
@ArogeG 
1. API gateway 4xx errors can be (rarely) the result of user actions and otherwise shouldn't happen operationally so I typically don't alert on those. Gateway 5xx errors are equivalent to the lambda errors we alert on, so no need to do both. No real need to alert on latency, if it gets too high we'll hit the lambda timeouts and see those transactions as errors anyways.  Some of these metrics like latency and concurrent executions are more about troubleshooting performance bottlenecks rather than for alerting.

2. Now that we fixed the timeout / performance issues causing errors, the alert isn't triggering so the current threshold is fine. We'll probably have to eventually tweak it in production when FAM has higher usage volumes, but no compelling reason to worry about that now from my point of view.

3. I kind of answered this in 1 - the dashboard provides the ability to monitor lambda execution time. We could add an alert if we wanted, if we had a clearly defined performance NFR (e.g. required by downstream applications) that would make it more relevant to have such an alert.

**Comment by ArogeG** [comment]
Thanks @basilv, as agreed on Scrum call please can you help with some high level documentation for recreating the dashboard & events in Prod and also please can you include the invocations (# of requests) to the dashboard.

**Comment by basilv** [comment]
I added documentation for the dashboard on the FAM Operations confluence page - see https://apps.nrs.gov.bc.ca/int/confluence/display/FSAST1/FAM+Operations#FAMOperations-MonitoringDashboard.
I've tweaked the dashboard to include request counts, and I expect more tweaks could be made.

**Comment by ArogeG** [comment]
Thanks @basilv

**Comment by ArogeG** [comment]
Thanks @basilv
