### ISSUE TITLE
Team discussion about Design tokens usage and  UI library

### ISSUE THREAD

**Issue by ArogeG** [bcgov/nr-forests-access-management#454]
**Describe the task**
Team discussion on which UI library we should use for FAM.

**Acceptance Criteria**
- [ ] A decision on which UI library we should use for FAM.

**Additional context**
- see Catherine's discussion items below.

**Comment by MCatherine1994** [comment]
Discussion items for fingerprint team:

- UI library for FAM:
   - bootstrap library options, they both built on top of bootstrap 5 with vue3, support typescript: 
        - bootstrap-vue-next, in alpha version, not officially published, but managed by the same team that builds bootstrapVue
        - mdb-vue-ui-kit
- How to get a tree view:
    - any bootstrap vue3 tree library?
    - or use the tree component from ant design, we could just import a single component from ant design
- How to apply the common style sheet
    - add the class name to our components

**Comment by basilv** [comment]
My comments from Discord: I've been thinking overnight about the design system challenge. I think a variant option that would be worth exploring is to see what's involved to use Carbon web components in Vue3. Based on my quick scan, it should be possible in theory, the main question is how easy or difficult this would be. Rather than starting with basic components like buttons, I'd propose starting with things like DatePicker that aren't in bootstrap anyway. 

There is a vue3 library under active development for integrating with Carbon, while it hasn't integrated all carbon components it is likely the best starting point: https://github.com/carbon-design-system/carbon-components-vue/blob/vNext/package.json. Another promising option is to leverage the Carbon Web Components library directly, but it appears its going to have a major new version soon so timing could be a bit better there: https://medium.com/carbondesign/coming-soon-carbon-web-components-v2-7decc1749f5d. (See https://github.com/carbon-design-system/issue-tracking/issues/121 on origins of using web components in Carbon, and see https://web-components.carbondesignsystem.com/ for list of carbon components available (in v1).
