### ISSUE TITLE
Integrate fam-idim-lookup-proxy with FAM for IDIR verfification

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-forests-access-management#679]
Description:
Implement verify function for IDIR in FAM

AC:
- Can search IDIR user by username to verify for IDIR (backend - new API endpoint)
- if found: display a green checkmark (frontend)
- if not found:  display error message (frontend)

Additional context:
User card component implementation to follow in separate issue

**Comment by ConradBoydElliottGustafson** [comment]
Confirmed that only Active IDIR accounts will return a result from the web service. As per Pathfinder SSO team.

**Comment by ianliuwk1019** [comment]
For current design of IDIM-Proxy, it only has an already hashed string as an api-key in the header ("X-API-KEY") needed.
The value need to be set in both repos.

**Comment by ianliuwk1019** [comment]
The "**requester**" (the user who login in FAM) is needed for backend to send a request to **IDIM-Lookup-Proxy**. FAM currently does not have direct information about this requester from **Cognito Access Token**. The access token does have "**username**" attribute (which mapped to "**cognito_user_id**" in **fam_user** database with this similar value: "**idir_b5ecdb094dfb4149a6a8445a01a96bf0@idir**" (The value gets inserted when user login).

While doing the integration, I found we can lookup the **requester** information by its "**cognito_user_id**" from the database. This has no problem in deployment environments, but locally will face problem because when user sign in at FAM frontend, the sign in user's "cognito_user_id" is saved in AWS DEV environment database, **NOT** on developer's local database. Developers will have problem doing user IDIR check (either from frontend FAM or swagger) because backend can't find who the requester is.

Few solutions are possible:
1. Passing entire token (contains not only access token, but id token) from frontend to our FAM resource server (backend). For this point, need to investigate how to adjust current backend jwt_validation code to take into account of the token structure change. (and possibly how it affect swagger UI)
2. Backend (somehow) exchange Access Token with AWS Cognito for ID Token. For this, more on how to integration with Cognito is required at jwt_validation code. Also for each request, it will need to call Cognito (maybe expensive/slow) and what if the service somehow isn't reachable.
3. Adjust token mapping on Access Token to provide necessary login user information. For this, not sure if possible, or by convention people do that but would possibly the easiest.

**Comment by ianliuwk1019** [comment]
Just a experimenting to try passing a user GUID instead of username to see if IDIM webservice work but get 400.
![image.png](https://images.zenhubusercontent.com/62a9ff93d8506f14758ef03a/3e9f1710-b2c9-48a2-becd-2f79d14d6e96)
![image.png](https://images.zenhubusercontent.com/62a9ff93d8506f14758ef03a/87efdf3e-16a1-41a1-b112-df6a28096426)

**Comment by ConradBoydElliottGustafson** [comment]
I ran into the same issue recently with the "no self-grant" ticket. I wrote it to look up the username in the database using the cognito ID.

In AWS, the easiest thing is to do a quick DB query for the username and pass it to the proxy. Hitting the user_info endpoint every time is extra processing but not really terrible. Passing the ID token from the front-end each time is also possible (as long as we validate that the cognito ID is matching the access token.

In local development mode, it really doesn't matter what gets passed to the IDIM web service. @MCatherine1994 has been hardcoding the value for testing purposes up until now. It only matters for the PROD version of the IDIM web service, but we shouldn't be hitting the PROD version from anywhere but our PROD instance anyway. We don't hit PROD from local environment (I hope!).

**Comment by ianliuwk1019** [comment]
I noticed and already used the DB query code to find the username to pass to the proxy.
Thanks to Basil's suggestion, I also code a mock user(requester) for ONLY local development need and for testing need to resolve the problem. Otherwise, imagine it will be painful for other developers doing local development (especially for frontend developers) to not able to search.

However, do we want to discuss this further? Or create a ticket if needed to see if we like to log (audit) on each request since our system is more security aware about who/when/what action/what reason(params) is accessing the system. Passing ID token seems to be the easy one it seems as it does not need to hit database and does not need to have extra request to Cognito. Only thing it need is to verify the ID token (and we probably already has all the code needed to verify it same as Access Token).  @basilv @ConradBoydElliottGustafson

**Comment by ianliuwk1019** [comment]
No need to do this but added a new ticket #729 for the "requester" improvement.
