### ISSUE TITLE
Transition to Operations - FAM

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-forests-access-management#710]
**Describe the task**
AS identified in the STRA, work with ITSM to get foundational items in place.

**Acceptance Criteria**
- [x] FAM Confluence page created (https://apps.nrs.gov.bc.ca/int/confluence/display/FAM/FAM+-+Forest+Access+Management)
- [x] First drafts of 'mandatory' items complete
- [ ] 

**Additional context**
- Jira reference https://apps.nrs.gov.bc.ca/int/jira/browse/PTS-287
- This will be an ongoing exercise as this issue is only for mandatory items and all information needs to be KEPT up to date

-'Mandatory' items (https://apps.nrs.gov.bc.ca/int/confluence/display/TS/Transition+to+Operations+List+of+Deliverables)
- [x] IRS updates
- [x]  Repos setup (only Github, IRS, AWS Secrets Manager - no Jira at this time)
- [x]  Support Model to be documented in Confluence

**Comment by basilv** [comment]
Pete, here's my fairly thorough review notes. I took a mostly longer-term / official perspective on most of it, which isn't all strictly necessary right now since the dev team is also the support team. 
- IRS has an entry for FAM with reasonable information. No application dependencies listed, not sure if that's important/necessary (normally I'd say yes as a support person.)
- Transition to Operations list of deliverables where I had review comments follows:
-- Support model in Confluence: 
--- Seems to reference https://apps.nrs.gov.bc.ca/int/confluence/display/FAM/FAM+-+Forest+Access+Management which is different from our 'main' FAM confluence site which is confusing to me. Should we move our main FAM confluence space into the 'official' site? Or at least cross-reference the two?
--- The documented process for incidents does reflect current state, but its unclear whether we are trying to evolve now towards a more formal operations structure. In any case, it isn't accurate to say that 'fam is in development' from a support perspective, FAM is live in production (and also undergoing active development). I'm suggesting we might want to define a 'business area support team', currently led by you Pete. 
--- I'd prefer for our documented process to at least briefly cover how issues (including security incidents) are logged - e.g. create a GitHub issue. We might want to have a clarification that details on sensitive security issues should be logged in Confluence, not put directly into GitHub.
--- Our process should cover how we engage the service desk (or whoever) to get support from other teams or raise a broader security issue?
-- User Setup Instructions - incomplete in Confluence
-- Access requirements for operational support members - incomplete/missing in Confluence. This is essentially a new team member onboarding guide, should cover off all the necessary systems including FAM prod itself, GitHub, AWS administrative access, Confluence, etc.
-- Developer Guide - missing (or at least not referenced on Support page).

**Comment by gormless87** [comment]
AS this issue was setup to complete the mandatory items in the  [Transition to Operations ](https://apps.nrs.gov.bc.ca/int/confluence/x/FAlTC) list of deliverables, it is _arguably_ complete.

Outstanding items as identified by Basil are

Documented process for incidents -- #296 
User Setup Instructions - will follow delegated admin design
New team member onboarding guide -- https://github.com/bcgov/nr-forests-access-management/issues/778


--Related to #296, Release Guide #486
https://github.com/bcgov/nr-forests-access-management/wiki/Release-Management
https://github.com/bcgov/nr-forests-access-management/wiki/Creating-a-Release

-- Developer Guide 
   --FAM Onboarding User Guide: https://github.com/bcgov/nr-forests-access-management/wiki/FAM-Onboarding
   --FAM Onboarding Ops Guide: https://github.com/bcgov/nr-forests-access-management/wiki/FAM-Onboarding-Ops-Guide
