### ISSUE TITLE
Segregate database access with multiple proxys 

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-forests-access-management#718]
**Describe the task**
For auth lambda use database user with limited permissions separate from database user for api lambda

**Acceptance Criteria**
- [x] Create new appropriately named database proxy account for auth lambda
- [x] Analyze required permissions for api lambda proxy account
- [x] reduce privileges for api lambda
- [x] generate sql scripts to create new auth lambda user
- [x] create new AWS Secret for auth lambda user
- [x] auth lambda connections use lower privileged db user 
- [x] api lambda connections use higher privileged db user

**Additional context**
- https://apps.nrs.gov.bc.ca/int/confluence/display/FSAST1/Improving+Security (#9 level 1)
- Additional design work needed to clarify if the auth/api labmda split is sufficient, or if further segregation is warranted.

**Comment by basilv** [comment]
I've started with a PR to create a separate auth lambda db user with restricted access.
The second step (not started yet) is to reduce the permissions of the API db user.

**Comment by basilv** [comment]
Auth lambda work is done. Reducing access of API DB user is in progress, see PR https://github.com/bcgov/nr-forests-access-management/pull/745

**Comment by basilv** [comment]
For the short term solution:
- Auth function: tests run with master db, since we want auth lambda user to be locked down as much as possible (and letting the tests run with auth lambda user requires opening up inserts on various tables)
- API function: tests run with API db user, the expansion of permissions to have tests run is reasonable - just some extra deletes. The work to refactor the tests to avoid these extra delete permissions has been descoped and moved to new issue #751.
