### ISSUE TITLE
Spike(Frontend): Navigation Guard and Data Fetching for Components.

### ISSUE THREAD

**Issue by ianliuwk1019** [bcgov/nr-forests-access-management#742]
**Describe the task**
A good practice for frontend **routes (pages) navigation** and **data fetching** is to use: "Guards". They sometimes work together. Data fetching can be "**before**" or "**after**" entering the **target route**, however, it comes down to User Experience.

But in previous experience, "**before**" is usually preferred. For example, if data fetching encounters issue and component is already active (or entered route), navigating user away probably isn't a good user experience. Also in some cases, if the user isn't allowed to enter the route (due to Token validation from backend) it is better to preventing the user from entering the route before the component is activated. Sometimes, some validations are necessary (frontend/backend) to protect from users entering the route(page/component) 

Using guards promotes a central place for reusable code for route protection and async data fetching handling, and it reduces spaghetti code in each component and reduces hard-to-deal bugs. For example, at GrantAccess component, the data fetching can possibly be adjusted and promoted in Guard.
![image.png](https://images.zenhubusercontent.com/62a9ff93d8506f14758ef03a/a66ab77a-ff3b-48a2-880e-aec4348a52fe)

Vue, like other frameworks (Angular, React) also has this as "[Navigation Guards](https://router.vuejs.org/guide/advanced/navigation-guards.html)". However, the way to use Guards is slightly different than Option API, seems for Vue's Composition API, it probably exposes some hooks for the component instead of coding it in Router.

Spike to: 
- understand what Vue Guards function(s) can be used for navigation at **component level**.
- how frontend can have guards that are **reusable** for components and in **central place**.
- any complication or big refactoring needs that could impact other components from the implementation. 
We could limit this spike to only navigation from dashboard into **GrantAccess** page.

**Additional context**
- Useful links: 
   [Navigation Guards](https://router.vuejs.org/guide/advanced/navigation-guards.html), 
   [Vue Router and the Composition API](https://router.vuejs.org/guide/advanced/composition-api.html#navigation-guards)
   [Data-Fetching](https://router.vuejs.org/guide/advanced/data-fetching.html)

- It may be nice to have global loading/spinner works (not necessary for this) for this.
- We do already use a Global Guard for all routes for token refreshing already but it is not for component level:
- ![image.png](https://images.zenhubusercontent.com/62a9ff93d8506f14758ef03a/7d764d57-0bcf-41c6-9651-fb8bb04bd968)

**Comment by J0taFerreira** [comment]
### Spike on Navigation Guards

**Navigation Guards in Component**
	
Composition API guards can be used in any component rendered by <router-view>. 
While it is possible to use in-component navigation guards with a setup function, we have only update and leave guards as Composition API.
In composition API the beforeRouteEnter is not possible as it is executed before a view component is mounted. When the setup function is called, the routing has already occurred.

- onBeforeRouteUpdate(() => {}) **onBeforeRouteUpdate** triggers on the same route (exemple: changing query, params, or hash). 
- onBeforeRouteLeave(() => {}) **onBeforeRouteLeave** is usually used to prevent the user from accidentally leaving the route with unsaved edits.
	
	
**Per-Route Guard**
	
beforeEnter is not in component level but may be one option on the absence of beforeRouteEnter.
It allow splitting guard logic in smaller functions and making it easy to chain them.
We can define beforeEnter directly on the route's configuration object. It only trigger when navigating from a different route, they don't trigger when the params, query or hash change.

 [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdFJnIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--8f9961a5ca291bbaf8cb4bdf16bd6b05a6a32e82/Screenshot%20from%202023-09-01%2010-37-45.png)

Also we can pass an array of functions to beforeEnter, this is useful when reusing guards for different routes:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdGRnIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d10262c75f0cf4f7a9e5fbc8cafb39671a0e7bb6/Screenshot%20from%202023-09-01%2010-37-58.png)

Some options if we need to get the data and/or want to stay on the old page due to an error:

-  beforeEnter + stateManager, 
- beforeEach + stateManger, 
- Use the options api

**Comment by MCatherine1994** [comment]
Hi Jota, could you please show us an example how to use the guard to replace the try-catch section in the onMounted method? So basically if we can use the guard to check if the login user has access to any application before direct the user to the dashboard page?

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBalZ1IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5e4f4c2c20cd9e07b4e20261275a7dc8dad6bf14/Screen%20Shot%202023-09-05%20at%204.32.48%20PM.png)

**Comment by ianliuwk1019** [comment]
Thanks Jota for a good summary.
I think it should be doable (using **beforeEnter**()) and I like Catherine's idea to implement an example to move onMounted() logic into a better reusable place before navigating to the component.

I feel (but not sure) Dashboard.vue is probably tricker because it is the first page that user sees after logged on. Either the user has role or has no role (like last time Olga was facing because she did not have a role and frontend popped an unclear error from backend). GrantAccess.vue probably is easier. But nonetheless, welcome to see an implementation on either one of them.

**Comment by MCatherine1994** [comment]
I think the idea is clear enough, even though we might need more detail discussion when we actually start to implement it. For example, in the code example, I feel only the get fam application role part needs to be in the guard, the rest part for assigning form data no need to be in the guard. But overall I think this spike is good. If @J0taFerreira feels this is doable and we better to have it, let's create a new ticket to implement it, thanks so much!!

 [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcXFSIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d5598c76ad2740dad050503c179b10e4b2298d50/Screen%20Shot%202023-09-12%20at%201.13.01%20PM.png)

**Comment by ianliuwk1019** [comment]
I left comment on this example pr: https://github.com/bcgov/nr-forests-access-management/pull/876
Implementation is doable, but a better design is needed.

**Comment by J0taFerreira** [comment]
I believe it is doable and agree that it really needs a better design.
