### ISSUE TITLE
Create FAM API Lambda with Python Code

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-forests-access-management#84]
As per #74:

port all of KN's code (replace example app with our actual API) (Deploy API as Lambda using Terraform bcgov/nr_fsa_fingerprint#48) 

AC:
-sample app incorporates all of KN's FAM API code
-all endpoints callable from CLI

Note: can test this from AWS CLI as this step is prior to api gateway setup

**Comment by explorertolu** [comment]
Kevin code has been incorporated into the sample project, it is currently in codeMigrade branch.

**Comment by franTarkenton** [comment]
hey @explorertolu was looking at the code that generates the zip package that ultimately gets run as a lambda function.  Another way that that build process could work, is instead of creating a virtualenv, and then pulling the necessary libs out of there and into the zip file, is you could run pip with the `-t` flag which would let you install the dependencies directly into the directory that is going to get zipped.  I'm not suggesting we change anything, just wanted to share this idea with you in case its of use.

**Comment by ArogeG** [comment]
New lambda function created with python code, still working on fixing errors.

**Comment by explorertolu** [comment]
The FAM API Lambda with Python Code has been deployed to AWS via Terraform, the Lambda function is called fam-api-kevin, it has also been connected to the database using AWS secret manager.

The API gateway is currently expose via AWS

**Comment by franTarkenton** [comment]
worked with Basil today.  Identified that the api hadn't been deployed and therefor wasn't available publicly.

**Comment by franTarkenton** [comment]
# Issue with developing / deploying Terraform.

In order to test a change to the terraform aws code, we have been invoking the github actions that are configured in our remote github repository to complete the terraform deployment, and ultimately determine if the terraform configuration is valid.  This involves submitting a pull request and then merging the pull request.  This is problematic because it requires a lot of steps in order to test what is potentially a trivial change.  Further to that we don't want to be merging code until a feature has been completed and has been reviewed.  And finally it can be really time consuming as we need to wait for a github runner, then once a runner is provided the code needs to complete the building of the lambda components, and finally it gets to the actual terraform deployment, which can also potentially wind up in a queue for terraform cloud to become available.

Options:

1. Running terraform locally.  Initially the idea was to be able to store the state locally to speed up the process of testing a terraform configuration.  Have since figured out how to invoke a deployment using terraform cloud from local dev env.  This allows us to re-use lambda packages, however the downside is it will require a copy of the logic used to build these components that currently resides in github action files.  Once this ticket is complete this the repo will include a markdown file describing how to set this up.

1. Having figured out how to init terraform with a remote backend allows the use of the commands: 
`terraform validate` and `terraform fmt` to identify syntax errors with terraform manifest files.

1. Breaking up deployments into multiple components to reduce the amount of time it takes for each deployment to complete.

1. Add logic to github actions to cache and reuse the lambda packages if the definitions haven't changed.

**Comment by franTarkenton** [comment]
In attempting to fix the gateway deployment started running into terraform deployment errors due to both the length of the github branch being used, and the fact that the branch name included a '/' character.  Attempted to resolve this inside of the variables.tf code, however terraform does not support the ability to create variables based on other variables.  Tried resolving this by calculating the variable as a 'locals' variable, however this did not support the ability to validate the variable and throw an error if the variable violated the constraints.

Modified approach by calculating the variable in the gha code, then passing the variable onto terraform.

**Comment by franTarkenton** [comment]
Used the debug GHA to verify that the API is deployed and publically available.  Ticket ready for review.
