### ISSUE TITLE
Draft terms and conditions

### ISSUE THREAD

**Issue by OlgaLiber2** [bcgov/nr-forests-access-management#882]
**Describe the task**
First draft of Terms and conditions 

**Acceptance Criteria**
- [x] understand the high level sections that need to go into the terms and conditions
- [x] understand the people the draft needs to go through (POs, directors, legal, etc) 
- [x] understand if the same terms and conditions will apply to all applications or if we need to have variations 

**Additional context**
- Add any other context about the task here.
- Or here

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbEdaIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ad744cb1515bba858e594c3a9bd606d8d33256f7/Terms%20and%20Conditions%20popup2.png)

**Comment by gormless87** [comment]
A related example of T&C for BC Gov: BC services Card [Terms of Use](https://www2.gov.bc.ca/gov/content/governments/government-id/bcservicescardapp/terms-of-use?keyword=terms&keyword=of&keyword=use)

A reasonable starter list of common clauses for T&C:  https://www.privacypolicies.com/blog/how-to-write-terms-conditions/#9_Common_Clauses_For_All_Terms_And_Conditions_Agreements

**Comment by gormless87** [comment]
Another T&C example is https://www.okta.com/sites/default/files/2022-02/MasterSubscriptionAgreement-English-Q1%20FY23.pdf

Basil's paraphrasing:

To paraphrase the below legalese, the main ideas here I think are:
-	User’s responsibility for their activities within FAM 
o	Immediate suspension of access if any activity in FAM’s judgement threatens the security, etc. of FAM
o	Will not attempt to gain unauthorized access, or disrupt the integrity / performance.
-	The section below on Security (2nd paragraph) – isn’t part of the T&Cs applied to the user, but is part of the ‘contract’ that FAM is providing to users. Arguably not necessary because all the applications choosing to use FAM are part of the ministry and thus these ‘contracts’ don’t need to be formally stated. So probably ignore.
-	Confidentiality statement is important. E.g. we don’t want a delegated admin to disclose who has access, list of BCeID names, etc.
-	Customer data section probably isn’t that relevant, but you (your legal team) might choose to have a statement that FAM’s intellectual property remains the property of the government (although the source code is published as open source, so this probably isn’t worth saying).
-	Customer indemnification obligation – for FAM we should be saying that the user is responsible for their actions, and will indemnify & defend the government from claims arising from the user’s actions. E.g. if a user (consultant for company A) inappropriately grants access to FOM/FOPs of A for a competitor B, and B tries to sue the government, then A needs to defend the government. Or something like that. I’m not a lawyer :)
-	A lawyer can better provide the formal legal stuff, but essentially you’ll have a statement specifying the duration of the agreement. The user can choose to ‘terminate’ the agreement by having their access to FAM revoked, but most T&Cs like confidentiality, responsibility for prior actions will continue to apply beyond termination. The user’s use of FAM will be considered ongoing acceptance of these T&Cs, but I’m assuming you’ll also get some explicit acceptance from each user
-	Remember to version the T&Cs (usually with a date and optionally a version number). Track user acceptance based on version # so if you need to majorly update the T&Cs, then you can explicitly get acceptance of the new T&Cs from existing users (if required).

**Comment by gormless87** [comment]
Created a Confluence page for the draft T&C - https://apps.nrs.gov.bc.ca/int/confluence/x/N4KyCg

**Comment by gormless87** [comment]
@OlgaLiber2 - I've made a few updates, please review/comment.

**Comment by OlgaLiber2** [comment]
@gormless87  I think it looks good. Can we write the next ticket to come up with draft wording for each of the points. I think it's ok to take the wording directly from https://www2.gov.bc.ca/gov/content/governments/government-id/bcservicescardapp/terms-of-use?keyword=terms&keyword=of&keyword=use for the sections that reference it. There is no need to reinvent the wheel, maybe we can let them know we're using some of their content. 

Once we have the draft we can book a meeting with Chantelle and Michelle to go over it.
